/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ex_TTYUtil */

#ifndef _Included_ex_TTYUtil
#define _Included_ex_TTYUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ex_TTYUtil
 * Method:    isTTY
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ex_TTYUtil_isTTY
  (JNIEnv *, jclass);

/*
 * Class:     ex_TTYUtil
 * Method:    getTTYName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ex_TTYUtil_getTTYName
  (JNIEnv *, jclass);

/*
 * Class:     ex_TTYUtil
 * Method:    getReptition
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ex_TTYUtil_getReptition
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     ex_TTYUtil
 * Method:    getAvg
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_ex_TTYUtil_getAvg
  (JNIEnv *, jclass, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
